version: '3.8'

services:
  api:
    build: .
    container_name: agentrag_api
    ports:
      - "8000:8000"
    env_file:
      - .env 

  discord_bot:
    build: .
    container_name: agentrag_bot
    command: ["python", "src/discord_bot.py"]
    env_file:
      - .env 